const $=id=>document.getElementById(id);
const SHAPES=['◆','▲','●','■'];
const state={
  names:['',''],rounds:12,round:1,points:[0,0],sips:[0,0],enabled:new Set(Object.keys(BANK)),deck:[],
  answers:{own:['','']},quizOptions:[[],[]],selected:[null,null],results:[null,null],phase:'question',handoff:null,sound:true
};
let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;});
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function clean(v,f){return v.trim().replace(/\s+/g,' ')||f}
function normalized(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function save(){try{localStorage.setItem('parejas-kahoot-v3',JSON.stringify({names:state.names,rounds:state.rounds,round:state.round,points:state.points,sips:state.sips,enabled:[...state.enabled],deck:state.deck,answers:state.answers,quizOptions:state.quizOptions,selected:state.selected,results:state.results,phase:state.phase,handoff:state.handoff,sound:state.sound}))}catch(e){}}
function clearSave(){localStorage.removeItem('parejas-kahoot-v3')}
function sound(type){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=type==='ok'?720:190;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.start();o.stop(c.currentTime+.22)}catch(e){}}
function confetti(){for(let i=0;i<30;i++){const x=document.createElement('span');x.className='confetti';x.textContent=['💗','✨','💜','🌸','💖'][i%5];x.style.left=Math.random()*100+'vw';x.style.animationDelay=Math.random()*.4+'s';x.style.fontSize=(13+Math.random()*17)+'px';document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}}
function renderCategories(){$('categories').innerHTML='';Object.keys(BANK).forEach(c=>{const b=document.createElement('button');b.className='cat';b.textContent=`${EMOJI[c]} ${c}`;b.onclick=()=>{if(state.enabled.has(c)){if(state.enabled.size===1){toast('Deja al menos una categoría');return}state.enabled.delete(c);b.classList.add('off')}else{state.enabled.add(c);b.classList.remove('off')}};$('categories').appendChild(b)})}
renderCategories();
document.querySelectorAll('[data-rounds]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-rounds]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.rounds=Number(b.dataset.rounds)});
function allQuestions(){let all=[];state.enabled.forEach(c=>BANK[c].forEach((q,i)=>all.push({id:`${c}-${i}`,category:c,text:q.text,options:q.options})));return all}
function makeDeck(){const all=shuffle(allQuestions());state.deck=[];while(state.deck.length<state.rounds)state.deck.push(...shuffle(all));state.deck=state.deck.slice(0,state.rounds)}
function currentQuestion(){return state.deck[state.round-1]}
function updateHeader(){const q=currentQuestion();$('scoreName1').textContent=state.names[0];$('scoreName2').textContent=state.names[1];$('score1').textContent=state.points[0];$('score2').textContent=state.points[1];$('sips1').textContent=state.sips[0];$('sips2').textContent=state.sips[1];$('roundText').textContent=`Ronda ${state.round} de ${state.rounds}`;const pct=Math.round(((state.round-1)/state.rounds)*100);$('progressText').textContent=pct+'%';$('progressBar').style.width=pct+'%';$('categoryLabel').textContent=`${EMOJI[q.category]} ${q.category}`;$('questionText').textContent=q.text;$('soundBtn').textContent=state.sound?'🔊':'🔇'}
function phaseCard(content){$('phaseContainer').innerHTML=`<div class="glass phase-card">${content}</div>`}
function handoff(player,next){state.phase='handoff';state.handoff={player,next};save();render()}
function buildOptions(correct){const q=currentQuestion();const distractors=shuffle(q.options.filter(v=>normalized(v)!==normalized(correct))).slice(0,3);for(const fallback of ['Otra opción','Ninguna de estas','Algo distinto']){if(distractors.length>=3)break;if(normalized(fallback)!==normalized(correct))distractors.push(fallback)}return shuffle([correct,...distractors.slice(0,3)])}
function optionButtons(options){return `<div class="kahoot-grid">${options.map((opt,i)=>`<button class="kahoot-option k${i}" data-choice="${i}"><span class="option-shape">${SHAPES[i]}</span><span>${escapeHtml(opt)}</span></button>`).join('')}</div>`}
function resultOptions(options,correct,guessed){return `<div class="result-options">${options.map((opt,i)=>{let cls=`result-option k${i}`;if(i===correct)cls+=' correct-option';else if(i===guessed)cls+=' wrong-option';else cls+=' dim-option';return `<div class="${cls}"><span>${SHAPES[i]}</span><b>${escapeHtml(opt)}</b>${i===correct?'<em>✓ Correcta</em>':i===guessed?'<em>Tu elección</em>':''}</div>`}).join('')}</div>`}
function render(){updateHeader();const n=state.names,p=state.phase;$('questionCard').classList.remove('hidden');
if(p==='question'){phaseCard(`<div class="phase-icon">🎮</div><div class="phase-title">Pregunta tipo Kahoot</div><p class="phase-help">Primero cada uno escribirá su respuesta verdadera en secreto. Después la aplicación la mezclará con otras tres opciones para que la pareja intente acertarla.</p><div class="actions"><button id="skipBtn" class="secondary">Cambiar pregunta 🔀</button><button id="beginBtn" class="primary">Empezar ronda</button></div>`);$('skipBtn').onclick=skipQuestion;$('beginBtn').onclick=()=>handoff(0,'own0');}
else if(p==='handoff'){const who=state.handoff.player;phaseCard(`<div class="handoff"><div class="phone">📱</div><h2>Pásale el móvil a ${escapeHtml(n[who])}</h2><p>La otra persona no debe mirar. Cuando ${escapeHtml(n[who])} tenga el teléfono, puede continuar.</p><button id="readyBtn" class="primary full">Ya lo tiene ${escapeHtml(n[who])}</button></div>`);$('questionCard').classList.add('hidden');$('readyBtn').onclick=()=>{state.phase=state.handoff.next;state.handoff=null;save();render()};}
else if(p==='own0'||p==='own1'){const i=p==='own0'?0:1;phaseCard(`<div class="phase-icon">🤫</div><div class="phase-title">Solo ${escapeHtml(n[i])}</div><p class="phase-help">Escribe tu respuesta real. Será la opción correcta que deberá encontrar ${escapeHtml(n[1-i])}.</p><div class="privacy">🔒 La respuesta se ocultará completamente</div><div class="field"><label>Tu respuesta verdadera</label><input id="writtenAnswer" class="input" maxlength="120" autocomplete="off" placeholder="Escribe tu respuesta..."/></div><button id="saveWritten" class="primary full">Guardar y ocultar 🔒</button>`);$('writtenAnswer').focus();$('saveWritten').onclick=()=>{const v=clean($('writtenAnswer').value,'');if(!v){toast('Escribe tu respuesta');return}state.answers.own[i]=v;if(i===0)handoff(1,'own1');else{state.quizOptions[0]=buildOptions(state.answers.own[1]);state.quizOptions[1]=buildOptions(state.answers.own[0]);handoff(0,'quiz0')}};}
else if(p==='quiz0'||p==='quiz1'){const i=p==='quiz0'?0:1,target=1-i,options=state.quizOptions[i],guess=state.selected[i];if(guess===null){phaseCard(`<div class="phase-icon">🧠</div><div class="phase-title">${escapeHtml(n[i])}, ¿qué escribió ${escapeHtml(n[target])}?</div><p class="phase-help">Marca una de las cuatro opciones. Solo una es la respuesta real.</p>${optionButtons(options)}`);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>chooseAnswer(i,target,Number(b.dataset.choice)));}else{const correctIndex=options.findIndex(v=>normalized(v)===normalized(state.answers.own[target])),ok=state.results[i];phaseCard(`<div class="comparison kahoot-result ${ok?'is-correct':'is-wrong'}"><div class="result-status">${ok?'✅ ¡CORRECTO!<small>+1 PUNTO</small>':'❌ INCORRECTO<small>SHOT 🥃</small>'}</div><h3>${escapeHtml(n[i])} respondió sobre ${escapeHtml(n[target])}</h3><p class="result-copy">${ok?'¡La conoces muy bien!':`La respuesta correcta era <b>${escapeHtml(state.answers.own[target])}</b>.`}</p>${resultOptions(options,correctIndex,guess)}</div><button id="continueQuiz" class="primary full" style="margin-top:14px">${i===0?`Ahora juega ${escapeHtml(n[1])} ➜`:'Terminar ronda ➜'}</button>`);$('continueQuiz').onclick=()=>{if(i===0)handoff(1,'quiz1');else{state.phase='roundDone';save();render();scrollTo({top:0,behavior:'smooth'})}};}}
else if(p==='roundDone'){phaseCard(`<div class="phase-icon">🏁</div><div class="phase-title">Ronda completada</div><p class="phase-help">Acierto = un punto. Fallo = SHOT.</p><div class="final-grid"><div class="final-card"><strong>${escapeHtml(n[0])}</strong><div class="big">${state.points[0]} pts</div><span>🥃 ${state.sips[0]} shots</span></div><div class="final-card"><strong>${escapeHtml(n[1])}</strong><div class="big">${state.points[1]} pts</div><span>🥃 ${state.sips[1]} shots</span></div></div><button id="nextBtn" class="primary full">${state.round===state.rounds?'Ver resultado final 🏆':'Siguiente ronda ➜'}</button>`);$('nextBtn').onclick=nextRound;}}
function chooseAnswer(i,target,choice){if(state.selected[i]!==null)return;state.selected[i]=choice;const chosen=state.quizOptions[i][choice],correct=state.answers.own[target];const ok=normalized(chosen)===normalized(correct);state.results[i]=ok;if(ok){state.points[i]++;sound('ok');confetti();if(navigator.vibrate)navigator.vibrate([60,40,60])}else{state.sips[i]++;sound('bad');if(navigator.vibrate)navigator.vibrate([180,70,180])}save();render();scrollTo({top:0,behavior:'smooth'})}
function skipQuestion(){const used=new Set(state.deck.slice(0,state.round-1).map(q=>q.id));const current=currentQuestion().id;const options=allQuestions().filter(q=>q.id!==current&&!used.has(q.id));if(!options.length){toast('No quedan preguntas nuevas');return}state.deck[state.round-1]=options[Math.floor(Math.random()*options.length)];resetRoundAnswers();save();render();toast('Pregunta cambiada')}
function resetRoundAnswers(){state.answers={own:['','']};state.quizOptions=[[],[]];state.selected=[null,null];state.results=[null,null]}
function nextRound(){if(state.round>=state.rounds){finish();return}state.round++;resetRoundAnswers();state.phase='question';save();render();scrollTo({top:0,behavior:'smooth'})}
function finish(){$('gameScreen').classList.add('hidden');$('finalScreen').classList.remove('hidden');clearSave();const n=state.names,p=state.points,s=state.sips;$('finalName1').textContent=n[0];$('finalName2').textContent=n[1];$('finalScore1').textContent=p[0];$('finalScore2').textContent=p[1];$('finalSips1').textContent=s[0];$('finalSips2').textContent=s[1];$('finalCard1').classList.remove('winner');$('finalCard2').classList.remove('winner');if(p[0]>p[1]){$('winnerText').textContent=`👑 ${n[0]} conoce mejor a ${n[1]}`;$('finalCard1').classList.add('winner')}else if(p[1]>p[0]){$('winnerText').textContent=`👑 ${n[1]} conoce mejor a ${n[0]}`;$('finalCard2').classList.add('winner')}else $('winnerText').textContent='🤝 Empate: os conocéis igual de bien';confetti();scrollTo({top:0,behavior:'smooth'})}
$('startBtn').onclick=()=>{if(!$('name2').value.trim()){toast('Escribe el segundo nombre');$('name2').focus();return}state.names=[clean($('name1').value,'Participante 1'),clean($('name2').value,'Participante 2')];state.round=1;state.points=[0,0];state.sips=[0,0];resetRoundAnswers();state.phase='question';makeDeck();$('setupScreen').classList.add('hidden');$('finalScreen').classList.add('hidden');$('gameScreen').classList.remove('hidden');save();render();scrollTo({top:0,behavior:'smooth'})};
$('againBtn').onclick=()=>{$('finalScreen').classList.add('hidden');$('setupScreen').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})};
$('quitBtn').onclick=()=>{if(confirm('¿Salir de la partida actual?')){clearSave();location.reload()}};
$('soundBtn').onclick=()=>{state.sound=!state.sound;save();updateHeader();toast(state.sound?'Sonido activado':'Sonido desactivado')};
$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else $('installModal').classList.remove('hidden')};$('closeInstall').onclick=()=>$('installModal').classList.add('hidden');$('installModal').onclick=e=>{if(e.target===$('installModal'))$('installModal').classList.add('hidden')};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
