const $=id=>document.getElementById(id);
const state={names:["",""],rounds:12,round:1,points:[0,0],sips:[0,0],enabled:new Set(Object.keys(BANK)),deck:[],answers:{own:["",""],guess:["",""]},judged:[null,null],phase:"question",handoff:null,sound:true};
let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;});
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function clean(v,f){return v.trim().replace(/\s+/g,' ')||f}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2100)}
function save(){try{localStorage.setItem('parejas-pwa-v1',JSON.stringify({names:state.names,rounds:state.rounds,round:state.round,points:state.points,sips:state.sips,enabled:[...state.enabled],deck:state.deck,answers:state.answers,judged:state.judged,phase:state.phase,sound:state.sound}))}catch(e){}}
function clearSave(){localStorage.removeItem('parejas-pwa-v1')}
function sound(type){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=type==='ok'?660:210;g.gain.setValueAtTime(.07,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch(e){}}
function confetti(){for(let i=0;i<28;i++){const x=document.createElement('span');x.className='confetti';x.textContent=['💗','✨','💜','🌸','💖'][i%5];x.style.left=Math.random()*100+'vw';x.style.animationDelay=Math.random()*.4+'s';x.style.fontSize=(13+Math.random()*17)+'px';document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}}
function renderCategories(){$('categories').innerHTML='';Object.keys(BANK).forEach(c=>{const b=document.createElement('button');b.className='cat';b.textContent=`${EMOJI[c]} ${c}`;b.onclick=()=>{if(state.enabled.has(c)){if(state.enabled.size===1){toast('Deja al menos una categoría');return}state.enabled.delete(c);b.classList.add('off')}else{state.enabled.add(c);b.classList.remove('off')}};$('categories').appendChild(b)})}
renderCategories();
document.querySelectorAll('[data-rounds]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-rounds]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.rounds=Number(b.dataset.rounds)});
function makeDeck(){let all=[];state.enabled.forEach(c=>BANK[c].forEach((text,i)=>all.push({id:`${c}-${i}`,category:c,text})));state.deck=shuffle(all).slice(0,state.rounds)}
function currentQuestion(){return state.deck[state.round-1]}
function updateHeader(){const q=currentQuestion();$('scoreName1').textContent=state.names[0];$('scoreName2').textContent=state.names[1];$('score1').textContent=state.points[0];$('score2').textContent=state.points[1];$('sips1').textContent=state.sips[0];$('sips2').textContent=state.sips[1];$('roundText').textContent=`Ronda ${state.round} de ${state.rounds}`;const pct=Math.round(((state.round-1)/state.rounds)*100);$('progressText').textContent=pct+'%';$('progressBar').style.width=pct+'%';$('categoryLabel').textContent=`${EMOJI[q.category]} ${q.category}`;$('questionText').textContent=q.text;$('soundBtn').textContent=state.sound?'🔊':'🔇'}
function phaseCard(content){$('phaseContainer').innerHTML=`<div class="glass phase-card">${content}</div>`}
function render(){updateHeader();const n=state.names;const p=state.phase;if(p==='question'){phaseCard(`<div class="phase-icon">🎯</div><div class="phase-title">Nueva pregunta para los dos</div><p class="phase-help">Cada persona responderá sobre sí misma en privado. Después intentaréis adivinar la respuesta de la otra.</p><div class="actions"><button id="skipBtn" class="secondary">Cambiar pregunta 🔀</button><button id="beginBtn" class="primary">Empezar ronda</button></div>`);$('skipBtn').onclick=skipQuestion;$('beginBtn').onclick=()=>handoff(0,'own0');}
else if(p==='handoff'){const who=state.handoff.player;phaseCard(`<div class="handoff"><div class="phone">📱</div><h2>Pásale el móvil a ${n[who]}</h2><p>Que la otra persona no mire la pantalla. Cuando ${n[who]} tenga el teléfono, puede continuar.</p><button id="readyBtn" class="primary full">Ya lo tiene ${n[who]}</button></div>`);$('questionCard').classList.add('hidden');$('readyBtn').onclick=()=>{state.phase=state.handoff.next;state.handoff=null;$('questionCard').classList.remove('hidden');save();render()};}
else if(p==='own0'||p==='own1'){const i=p==='own0'?0:1;phaseCard(`<div class="phase-icon">🤫</div><div class="phase-title">Solo ${n[i]}</div><p class="phase-help">Responde sobre ti. Al guardar, tu respuesta se ocultará por completo.</p><div class="privacy">🔒 Nadie más debe ver esta respuesta</div><div class="field"><label>Tu respuesta secreta</label><textarea id="answerInput" maxlength="220" placeholder="Escribe aquí..."></textarea></div><button id="saveAnswer" class="primary full">Guardar y ocultar 🔒</button>`);$('answerInput').focus();$('saveAnswer').onclick=()=>{const v=$('answerInput').value.trim();if(!v){toast('Escribe tu respuesta');return}state.answers.own[i]=v;save();if(i===0)handoff(1,'own1');else handoff(0,'guess0')};}
else if(p==='guess0'||p==='guess1'){const i=p==='guess0'?0:1,other=1-i;phaseCard(`<div class="phase-icon">🧠</div><div class="phase-title">${n[i]}, adivina a ${n[other]}</div><p class="phase-help">¿Qué crees que respondió ${n[other]} a esta pregunta?</p><div class="field"><label>Tu respuesta sobre ${n[other]}</label><textarea id="answerInput" maxlength="220" placeholder="Creo que respondió..."></textarea></div><button id="saveGuess" class="primary full">Guardar mi apuesta ✨</button>`);$('answerInput').focus();$('saveGuess').onclick=()=>{const v=$('answerInput').value.trim();if(!v){toast('Escribe lo que crees');return}state.answers.guess[i]=v;save();if(i===0)handoff(1,'guess1');else{state.phase='reveal';save();render()}};}
else if(p==='reveal'){const card=(guesser,target)=>`<div class="comparison"><h3>¿${n[guesser]} conoce a ${n[target]}?</h3><div class="answer real"><small>Respuesta real de ${n[target]}</small><p>${escapeHtml(state.answers.own[target])}</p></div><div class="answer"><small>Lo que dijo ${n[guesser]}</small><p>${escapeHtml(state.answers.guess[guesser])}</p></div><div class="judge"><button class="yes" data-i="${guesser}" data-ok="1">✅ Acertó</button><button class="no" data-i="${guesser}" data-ok="0">🥃 Falló</button></div></div>`;phaseCard(`<div class="phase-title">Revelación de respuestas 👀</div><p class="phase-help">Cada persona decide si la respuesta de la otra es suficientemente correcta.</p><div class="reveal-grid">${card(0,1)}${card(1,0)}</div><button id="nextBtn" class="primary full" style="margin-top:14px" disabled>${state.round===state.rounds?'Ver resultado 🏆':'Siguiente ronda ➜'}</button>`);document.querySelectorAll('[data-ok]').forEach(b=>b.onclick=()=>judge(Number(b.dataset.i),b.dataset.ok==='1',b));$('nextBtn').onclick=nextRound;}}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function handoff(player,next){state.phase='handoff';state.handoff={player,next};save();render()}
function skipQuestion(){const used=new Set(state.deck.slice(0,state.round-1).map(q=>q.id));const current=currentQuestion().id;let pool=[];state.enabled.forEach(c=>BANK[c].forEach((text,i)=>pool.push({id:`${c}-${i}`,category:c,text})));const options=pool.filter(q=>q.id!==current&&!used.has(q.id));if(!options.length){toast('No quedan preguntas nuevas');return}state.deck[state.round-1]=options[Math.floor(Math.random()*options.length)];save();render();toast('Pregunta cambiada')}
function judge(i,ok,btn){if(state.judged[i]!==null)return;state.judged[i]=ok;if(ok){state.points[i]++;sound('ok');confetti()}else{state.sips[i]++;sound('bad')}btn.classList.add('selected');btn.parentElement.querySelectorAll('button').forEach(x=>x.disabled=true);updateHeader();if(state.judged.every(x=>x!==null))$('nextBtn').disabled=false;save()}
function nextRound(){if(state.round>=state.rounds){finish();return}state.round++;state.answers={own:['',''],guess:['','']};state.judged=[null,null];state.phase='question';save();render();scrollTo({top:0,behavior:'smooth'})}
function finish(){$('gameScreen').classList.add('hidden');$('finalScreen').classList.remove('hidden');clearSave();const n=state.names,p=state.points,s=state.sips;$('finalName1').textContent=n[0];$('finalName2').textContent=n[1];$('finalScore1').textContent=p[0];$('finalScore2').textContent=p[1];$('finalSips1').textContent=s[0];$('finalSips2').textContent=s[1];$('finalCard1').classList.remove('winner');$('finalCard2').classList.remove('winner');if(p[0]>p[1]){$('winnerText').textContent=`👑 ${n[0]} conoce mejor a ${n[1]}`;$('finalCard1').classList.add('winner')}else if(p[1]>p[0]){$('winnerText').textContent=`👑 ${n[1]} conoce mejor a ${n[0]}`;$('finalCard2').classList.add('winner')}else $('winnerText').textContent='🤝 Empate: os conocéis igual de bien';confetti();scrollTo({top:0,behavior:'smooth'})}
$('startBtn').onclick=()=>{if(!$('name2').value.trim()){toast('Escribe el segundo nombre');$('name2').focus();return}state.names=[clean($('name1').value,'Participante 1'),clean($('name2').value,'Participante 2')];state.round=1;state.points=[0,0];state.sips=[0,0];state.answers={own:['',''],guess:['','']};state.judged=[null,null];state.phase='question';makeDeck();$('setupScreen').classList.add('hidden');$('finalScreen').classList.add('hidden');$('gameScreen').classList.remove('hidden');save();render();scrollTo({top:0,behavior:'smooth'})};
$('againBtn').onclick=()=>{$('finalScreen').classList.add('hidden');$('setupScreen').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})};
$('quitBtn').onclick=()=>{if(confirm('¿Salir de la partida actual?')){clearSave();location.reload()}};
$('soundBtn').onclick=()=>{state.sound=!state.sound;save();updateHeader();toast(state.sound?'Sonido activado':'Sonido desactivado')};
$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else $('installModal').classList.remove('hidden')};$('closeInstall').onclick=()=>$('installModal').classList.add('hidden');$('installModal').onclick=e=>{if(e.target===$('installModal'))$('installModal').classList.add('hidden')};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
